---
- name: Create validator startup script
  ansible.builtin.template:
    src: validator.startup.j2
    dest: "{{ validator_script_path }}"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    mode: '0755'

- name: Create validator systemd service
  ansible.builtin.template:
    src: validator.service.j2
    dest: "/etc/systemd/system/{{ validator_service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create logrotate configuration
  ansible.builtin.template:
    src: validator.logrotate.j2
    dest: "/etc/logrotate.d/{{ validator_service_name }}"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create logrotate service
  ansible.builtin.template:
    src: validator-logrotate.service.j2
    dest: "/etc/systemd/system/{{ validator_service_name }}-logrotate.service"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create logrotate timer
  ansible.builtin.template:
    src: validator-logrotate.timer.j2
    dest: "/etc/systemd/system/{{ validator_service_name }}-logrotate.timer"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable and start validator service
  ansible.builtin.systemd:
    name: "{{ validator_service_name }}"
    state: started
    enabled: true

- name: Enable logrotate timer
  ansible.builtin.systemd:
    name: "{{ validator_service_name }}-logrotate.timer"
    state: started
    enabled: true
  become: true
