---
# Ensure the host architecture is set (required for conditional installation logic)
- import_tasks: ../common/tasks/set_host_architecture.yml

- name: Install build prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - at
      - bzip2
      - libssl-dev
      - libudev-dev
      - pkg-config
      - zlib1g-dev
      - llvm
      - libclang-dev
      - clang
      - cmake
      - make
      - libprotobuf-dev
      - protobuf-compiler
    update_cache: true

# Set local boolean for build method
- name: Set local boolean for build method
  ansible.builtin.set_fact:
    build_from_source_bool: "{{ build_from_source | default(false) | bool }}"

- name: Install Jito-Solana from binaries
  import_tasks: install_from_binaries.yml
  when: not build_from_source_bool

- name: Build and install Jito from source
  import_tasks: install_from_source.yml
  when: build_from_source_bool

- name: Install - Ensure Solana CLI bin path is in .bashrc
  ansible.builtin.lineinfile:
    path: "$HOME/.bashrc"
    line: 'export PATH="{{ solana_install_dir }}:$PATH"'
    create: yes
    state: present

- name: Install - Ensure Solana CLI bin path is in .zshrc
  ansible.builtin.lineinfile:
    path: "$HOME/.zshrc"
    line: 'export PATH="{{ solana_install_dir }}:$PATH"'
    create: yes
    state: present

- name: Installation complete
  debug:
    msg: >-
      Jito-Solana {{ jito_version }} has been successfully installed
      {% if build_from_source_bool %}
      (built from source)
      {% else %}
      (from binaries)
      {% endif %}
