---
- name: Configure Jito-Solana validator
  ansible.builtin.debug:
    msg: "Starting Jito-Solana validator configuration"
  tags: [solana_validator_jito, configure]

- name: Set validator_keyset_name default if not defined
  ansible.builtin.set_fact:
    validator_keyset_name: "{{ validator_name }}"
  when: validator_keyset_name is not defined

- name: Install validator keyset using shared task
  ansible.builtin.import_tasks: ../solana_validator_shared/tasks/install_validator_keyset.yml
  tags: [solana_validator_jito, configure]

- name: Prepare the startup scripts for the validator
  ansible.builtin.import_tasks: jito_client/configure/prep_startup.yml
  tags: [solana_validator_jito, configure]

- name: Import log rotation configuration
  ansible.builtin.import_tasks: jito_client/configure/config_logrotate.yml
  tags: [solana_validator_jito, configure]

- name: Setup the watchdog service to start and monitor the validator using the startup script
  ansible.builtin.import_tasks: jito_client/configure/config_watchdog.yml
  tags: [solana_validator_jito, configure]

- name: Configuration complete
  ansible.builtin.debug:
    msg: "Jito-Solana validator configuration completed successfully"
  tags: [solana_validator_jito, configure]
